### ISSUE TITLE
[SECURITY] Arithmetic operation overflow in SELFDESTRUCT opcode

### ISSUE THREAD

**Issue by pventuzelo** [lambdaclass/lambda_ethereum_rust#1147]
Our team (@fuzzinglabs) discovered a bug was identified in the [op_selfdestruct](https://github.com/lambdaclass/lambda_ethereum_rust/blob/main/crates/vm/levm/src/opcode_handlers/system.rs#L296) function, which does not check for any overflow.

# Root cause

```rust
pub fn op_selfdestruct(
        &mut self,
        current_call_frame: &mut CallFrame,
    ) -> Result<OpcodeSuccess, VMError> {
        ...
        let mut target_account = self.get_account(&target_address);
        if target_account.is_empty() {
            gas_cost += dynamic_gas_cost;
        }
        target_account.info.balance += current_account_balance;
		...

        Ok(OpcodeSuccess::Result(ResultReason::SelfDestruct))
  }

```

`target_account.info.balance += current_account_balance;` : The value of current_account_balance has no check for overflow, causing a panic in the executor.

# Step to reproduce

Add to [[test](https://github.com/lambdaclass/lambda_ethereum_rust/blob/main/crates/vm/levm/tests/tests.rs)](https://github.com/lambdaclass/lambda_ethereum_rust/blob/main/crates/vm/levm/tests/tests.rs) : 

```rust
#[test]
fn test_arithmetic_operation_overflow_selfdestruct() {
    let mut vm = new_vm_with_bytecode(Bytes::copy_from_slice(&[50, 255]));
    let mut current_call_frame = vm.call_frames.pop().unwrap();
    vm.execute(&mut current_call_frame);
}
```

# Backtrace

```rust
--- tests::test_arithmetic_operation_overflow_selfdestruct stdout ----
thread 'tests::test_arithmetic_operation_overflow_selfdestruct' panicked at /home/.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/primitive-types-0.12.2/src/lib.rs:38:1:
arithmetic operation overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/std/src/panicking.rs:658:5
   1: core::panicking::panic_fmt
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/core/src/panicking.rs:74:14
   2: <primitive_types::U256 as core::ops::arith::AddAssign>::add_assign
             at /home/.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/uint-0.9.5/src/uint.rs:1403:5
   3: ethereum_rust_levm::opcode_handlers::system::<impl ethereum_rust_levm::vm::VM>::op_selfdestruct
             at ./src/opcode_handlers/system.rs:340:9
   4: ethereum_rust_levm::vm::VM::execute
             at ./src/vm.rs:244:41
   5: lib::tests::test_arithmetic_operation_overflow_selfdestruct
             at ./tests/tests.rs:76:5
   6: lib::tests::test_arithmetic_operation_overflow_selfdestruct::{{closure}}
             at ./tests/tests.rs:72:53
   7: core::ops::function::FnOnce::call_once
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/core/src/ops/function.rs:250:5
```

**Comment by ilitteri** [comment]
Thanks! Fixed in https://github.com/lambdaclass/lambda_ethereum_rust/pull/1095.
