### ISSUE TITLE
[SECURITY] Attempt to add with overflow in RETURNDATACOPY opcode

### ISSUE THREAD

**Issue by mhoste51** [lambdaclass/lambda_ethereum_rust#1153]
Our team at [FuzzingLabs](https://github.com/FuzzingLabs) discovered a bug in the [op_returndatacopy](https://github.com/lambdaclass/lambda_ethereum_rust/blob/39f3dceae351c1ff1073367dc1ccc878400fcbb0/crates/vm/levm/src/opcode_handlers/environment.rs#L398) function, this bug can lead to a panic when calculating minimum_word_size.

# Root cause

```rust
    // RETURNDATACOPY operation
    pub fn op_returndatacopy(
        &mut self,
        current_call_frame: &mut CallFrame,
    ) -> Result<OpcodeSuccess, VMError> {
        let dest_offset: usize = current_call_frame
            .stack
            .pop()?
            .try_into()
            .unwrap_or(usize::MAX);
        let returndata_offset: usize = current_call_frame
            .stack
            .pop()?
            .try_into()
            .unwrap_or(usize::MAX);
        let size: usize = current_call_frame
            .stack
            .pop()?
            .try_into()
            .unwrap_or(usize::MAX);

        let minimum_word_size = (size + WORD_SIZE - 1) / WORD_SIZE;
        let memory_expansion_cost = current_call_frame.memory.expansion_cost(
            dest_offset
                .checked_add(size)
                .ok_or(VMError::MemoryLoadOutOfBounds)?,
        )?;
        let gas_cost = gas_cost::RETURNDATACOPY_STATIC
            + gas_cost::RETURNDATACOPY_DYNAMIC_BASE * minimum_word_size
            + memory_expansion_cost;

        self.increase_consumed_gas(current_call_frame, gas_cost)?;

        if size == 0 {
            return Ok(OpcodeSuccess::Continue);
        }

        let sub_return_data_len = current_call_frame.sub_return_data.len();
        let data = if returndata_offset < sub_return_data_len {
            current_call_frame.sub_return_data.slice(
                returndata_offset
                    ..(returndata_offset
                        .checked_add(size)
                        .ok_or(VMError::MemoryLoadOutOfBounds)?)
                    .min(sub_return_data_len),
            )
        } else {
            vec![0u8; size].into()
        };

        current_call_frame.memory.store_bytes(dest_offset, &data)?;

        Ok(OpcodeSuccess::Continue)
    }
```

`let minimum_word_size = (size + WORD_SIZE - 1) / WORD_SIZE;`We can control`size`and give a value equal to`usize::MAX`. Since`WORD_SIZE = 32`, when we attempt to add`usize::MAX + 32`, we encounter an overflow because`minimum_word_size`is also a`usize`.

# Step to reproduce

### Payload

```rust
[50, 49, 48, 51, 62]

ORIGIN
BALANCE
ADDRESSE
CALLER
RETURNDATACOPY
```

Add to [test](https://github.com/lambdaclass/lambda_ethereum_rust/blob/main/crates/vm/levm/tests/tests.rs) : 

```rust
#[test]
fn test_overflow_returndatacopy() {
    let mut vm = new_vm_with_bytecode(Bytes::copy_from_slice(&[50, 49, 48, 51, 62]));
    let mut current_call_frame = vm.call_frames.pop().unwrap();
    vm.execute(&mut current_call_frame);
}
```

# Backtrace

```rust
---- tests::test_overflow_returndatacopy stdout ----
thread 'tests::test_overflow_returndatacopy' panicked at crates/vm/levm/./src/opcode_handlers/environment.rs:419:34:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/std/src/panicking.rs:658:5
   1: core::panicking::panic_fmt
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_const::panic_const_add_overflow
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/core/src/panicking.rs:181:21
   3: ethereum_rust_levm::opcode_handlers::environment::<impl ethereum_rust_levm::vm::VM>::op_returndatacopy
             at ./src/opcode_handlers/environment.rs:419:34
   4: ethereum_rust_levm::vm::VM::execute
             at ./src/vm.rs:175:43
   5: lib::tests::test_overflow_returndatacopy
             at ./tests/tests.rs:50:5
   6: lib::tests::test_overflow_returndatacopy::{{closure}}
             at ./tests/tests.rs:47:34
   7: core::ops::function::FnOnce::call_once
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/core/src/ops/function.rs:250:5
```

**Comment by ilitteri** [comment]
Thanks! Fixed in https://github.com/lambdaclass/lambda_ethereum_rust/issues/1095.
