### ISSUE TITLE
[SECURITY] Arithmetic operation overflow in call opcode

### ISSUE THREAD

**Issue by mhoste51** [lambdaclass/lambda_ethereum_rust#1155]
Our team at [FuzzingLabs](https://github.com/FuzzingLabs) discovered a bug in the [generic_call](https://github.com/lambdaclass/lambda_ethereum_rust/blob/main/crates/vm/levm/src/vm.rs#L516) function. This bug can lead to a panic when adding a value to the balance if it is equal to `u256::MAX`.

# Root cause

```rust
pub fn generic_call(
        &mut self,
        current_call_frame: &mut CallFrame,
        gas_limit: U256,
        value: U256,
        msg_sender: Address,
        to: Address,
        code_address: Address,
        _should_transfer_value: bool,
        is_static: bool,
        args_offset: usize,
        args_size: usize,
        ret_offset: usize,
        ret_size: usize,
    ) -> Result<OpcodeSuccess, VMError> {
        let mut sender_account = self.get_account(&current_call_frame.msg_sender);

        if sender_account.info.balance < value {
            current_call_frame.stack.push(U256::from(REVERT_FOR_CALL))?;
            return Ok(OpcodeSuccess::Continue);
        }

        let mut recipient_account = self.get_account(&to);

        // transfer value
        sender_account.info.balance -= value;
        recipient_account.info.balance += value;

        let code_address_bytecode = self.get_account(&code_address).info.bytecode;
				...
}
```

`recipient_account.info.balance += value;` Due to the lack of checks, if the recipient's balance is equal to U256::MAX, an overflow can occur when adding the value, triggering a panic.

# Step to reproduce

### Payload

```rust
[61, 48, 56, 54, 51, 51, 51, 241]

RETURNDATASIZE
ADDRESS
CODESIZE
CALLDATASIZE
CALLER
CALLER
CALLER
CALL

```

Add to [test](https://github.com/lambdaclass/lambda_ethereum_rust/blob/main/crates/vm/levm/tests/tests.rs) : 

```rust
#[test]
fn test_overflow_call() {
    let mut vm = new_vm_with_bytecode(Bytes::copy_from_slice(&[61, 48, 56, 54, 51, 51, 51, 241]));
    let mut current_call_frame = vm.call_frames.pop().unwrap();
    vm.execute(&mut current_call_frame);
}
```

# Backtrace

```rust
---- tests::test_overflow_call stdout ----
thread 'tests::test_overflow_call' panicked at /home/mhoste/.cargo/registry/src/index.crates.io-6f17d22bba15001f/primitive-types-0.12.2/src/lib.rs:38:1:
arithmetic operation overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/std/src/panicking.rs:658:5
   1: core::panicking::panic_fmt
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/core/src/panicking.rs:74:14
   2: <primitive_types::U256 as core::ops::arith::AddAssign>::add_assign
             at /home/mhoste/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uint-0.9.5/src/uint.rs:1403:5
   3: ethereum_rust_levm::vm::VM::generic_call
             at ./src/vm.rs:542:9
   4: ethereum_rust_levm::opcode_handlers::system::<impl ethereum_rust_levm::vm::VM>::op_call
             at ./src/opcode_handlers/system.rs:87:9
   5: ethereum_rust_levm::vm::VM::execute
             at ./src/vm.rs:223:33
   6: lib::tests::test_overflow_call
             at ./tests/tests.rs:50:5
   7: lib::tests::test_overflow_call::{{closure}}
             at ./tests/tests.rs:47:24
   8: core::ops::function::FnOnce::call_once
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/core/src/ops/function.rs:250:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/59e2c01c2217a01546222e4d9ff4e6695ee8a1db/library/core/src/ops/function.rs:250:5
```

**Comment by ilitteri** [comment]
Thanks! Resolved in https://github.com/lambdaclass/lambda_ethereum_rust/issues/1095.
